version: '3.8'

services:
  frontend:
    build:
      context: ./src/web/page
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src/web/page:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      - backend

  backend:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    ports:
      - "8080:5000"
    volumes:
      - ./src/api:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: netspinup
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: netspinup
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
