version: '3.8'

services:
  frontend:
    build:
      context: ./src/web/page
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:5000
    volumes:
      - ./src/web/page:/app
      - /app/node_modules

  backend:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/netspinup
    volumes:
      - ./src/api:/app
      - /app/node_modules

  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: netspinup
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
