version: '3.8'

services:
  backend:
    build:
      context: ./src/api
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: production
    restart: unless-stopped

  frontend:
    build:
      context: ./src/web/page
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
